### ISSUE TITLE
Need support for submodules in source tarballs.

### ISSUE THREAD

**Issue by awood** [rpm-software-management/tito#150]
The [sat5to6](http://github.com/candlepin/sat5to6) tool uses git submodules and the code within those submodules needs to be packaged.  Unfortunately, git archive does not descend into submodules.  There are suggestions on ways to address the problem on [StackOverflow](http://stackoverflow.com/questions/5482544) and there is also a solution in Python at https://github.com/Kentzo/git-archive-all.

Git archive does not support dereferencing symlinks either (although tar does), so this might be a good opportunity to add an archiver plugin where users can provide a class that will insert additional content into the source tarball.

**Comment by areese** [comment]
This PR adds an implementation of a submodule aware builder, please let me know your thoughts:
https://github.com/rpm-software-management/tito/pull/406

**Comment by FrostyX** [comment]
> This PR adds an implementation of a submodule aware builder

PR already merged and released. I am closing now, feel free to reopen if the issue remains.
