### ISSUE TITLE
tito tag --keep-version doesn't respect release version

### ISSUE THREAD

**Issue by dLobatog** [rpm-software-management/tito#186]
Reproduce by creating a spec with a version & release above 1, say 1.2.4-2.
Run `tito tag --keep-version`. It should tag 1.2.4-2. Instead, it tries to tag 1.2.5.-1.

**Comment by dgoodwin** [comment]
Expected behavior I'm afraid. When tagging a new version there is no reason to preserve a release > 1 AFAIK. I.e. It's not the second rpm release of 1.2.5, its the first. I would expect it to reset.

**Comment by eLobato** [comment]
Oh it's not that I want to get 1.2.5-2, I would like tito to respect the spec and tag `1.2.4-2` as I'm indicating in the spec. Isn't the `--keep-version` parameter supposed not to modify the spec at all?

**Comment by dgoodwin** [comment]
My mistake, indeed it should respect that with keep version.

**Comment by dLobatog** [comment]
Any updates?

**Comment by dgoodwin** [comment]
Nobody working on this afaik.

**Comment by FrostyX** [comment]
Hello @dLobatog,
It seems that the issue was already fixed. I am not able to reproduce it.

    $ rpm -q --qf "%{RELEASE}\n" --specfile enum.spec | head -1
    5.fc30

    $ tito tag --keep-version
    Creating output directory: /tmp/tito
    Tagging new version of subproject-enum: 1.3-4 -> 1.3-5
    Created tag: subproject-enum-1.3-5
    View: git show HEAD
    Undo: tito tag -u
    Push: git push --follow-tags origin

    $ rpm -q --qf "%{RELEASE}\n" --specfile enum.spec | head -1
    5.fc30

If it still happens to you, feel free to reopen.
