### ISSUE TITLE
[RFE] prepare patches

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/tito#193]
What I have:
- 1 upstream repo
- some number of patches for Fedora
- 1 fedora repo

I'd want to have my own git repo which will combine upstream repo + my patches and I want automate updating releases in fedora. i.e.
1. get tag
2. do git format-patch
3. add patches to spec file

Hope I described enough.

**Comment by ignatenkobrain** [comment]
For example, Debian does: http://http.debian.net/debian/pool/main/m/mesa/mesa_10.6.3.orig.tar.gz http://http.debian.net/debian/pool/main/m/mesa/mesa_10.6.3-1.diff.gz http://http.debian.net/debian/pool/main/m/mesa/mesa_10.6.3-1.dsc

orig.tar.gz has upstream sources
diff.gz is one diff for sources

I'd like to get tito making archive from original commits and get patches for current commit

**Comment by xsuchy** [comment]
1. clone upstream git
2. tito init
3. (this step do with default version tagger) tito tag
3. set builder class in tito.props to tito.distributionbuilder.DistributionBuilder and change tagger to ReleaseTagger.
4. do changes directly in git
5. tito release - this will automatically create patches and put them in spec file,while preserving pristine tar file

**Comment by ignatenkobrain** [comment]
@xsuchy thanks, how I should come with updating this? I mean after upstream will release new version?

**Comment by xsuchy** [comment]
@ignatenkobrain The idea is that you work in branches derived from master. I.e. when new upstream release is available you will leave old branch, and you will create new branch from upstream one, and do:
* (this step do with default version tagger) tito tag
* set builder class in tito.props to tito.distributionbuilder.DistributionBuilder and change tagger to ReleaseTagger.
* do changes directly in git
* tito release - this will automatically create patches and put them in spec file,while preserving pristine tar file

as previously. Just in new branch.

**Comment by ktdreyer** [comment]
This sounds similar to how we mananage patching with https://github.com/openstack-packages/rdopkg , where there's a clear distinction between "upstream repository", "fedora patches repository", and "dist-git repository".

**Comment by FrostyX** [comment]
This seems to be answered by @xsuchy, I am closing. Feel free to reopen if this is still an issue.
