### ISSUE TITLE
Mead builds should be able to push to branches

### ISSUE THREAD

**Issue by awood** [rpm-software-management/tito#194]
Right now Mead builds always push to master of the MEAD_SCM location.  This practice works for current builds but is not practical for build hotfixes based on earlier code.  The Mead releaser should be able to take a branch as an argument and push to that branch.

**Comment by nikosmoum** [comment]
Any chance this can be added to the agenda for any of the upcoming releases?

**Comment by nikosmoum** [comment]
@FrostyX You are right, this should work as you say. But after looking into it more, I realized I was looking for something different.
Right now, when syncing the repo of the mead build with the remote, only the tag is being pushed: 
https://github.com/rpm-software-management/tito/blob/7177422ec9ebb7fddb032905b8b7f2ad4037ebc7/src/tito/release/distgit.py#L554-L555
It would be nice if this pushed both the branch & tag we are on ( `git push --follow-tags <push_url> <current_local_branch>`)

**Comment by nikosmoum** [comment]
I created a PR for that: https://github.com/rpm-software-management/tito/pull/417

**Comment by FrostyX** [comment]
The PR #417 is merged, so this should work now.
