### ISSUE TITLE
question: how to copr build upstream of F23 odb?

### ISSUE THREAD

**Issue by finjulhich** [rpm-software-management/tito#202]
F23 provides the odb-2.4.0 package. This is its git repo:
git://pkgs.fedoraproject.org/odb.git
I would like to build with CORP a version of odb rpm that comes from 
git://scm.codesynthesis.com/odb/odb.git
I understand tito can help create the srpm to upload to COPR?
The steps in "How to create new release of RPM package in 5 seconds" didn't quite work.
I have tito installed on my F23.

**Comment by xsuchy** [comment]
Define "didn't quite work".

**Comment by finjulhich** [comment]
I happen to have created a makerpm user on my laptop.
I have the usual rpmbuild/BUILD RPMS SOURCES SPECS SRPMS   directory structure.
I am not sure I need it as I would want COPR to build the rpms for me.

Anyways, inside SOURCES, I did
    git clone git://scm.codesynthesis.com/odb/odb.git
so now I have SOURCES/odb
I went inside that and used tito.
   tito init
   tito tag

Already, at this stage, I don't think that's how I should be doing things.

**Comment by dgoodwin** [comment]
You shouldn't need to create that rpmbuild directory structure but where you clone the repo doesn't matter much, it should still work with what you did. You need to keep going though, what went wrong. :)

**Comment by finjulhich** [comment]
ok, tito init worked. Before I do tito tag (which failed):
I see there's no spec file inside SOURCES/odb.
Granted this is not exactly a tito question, but I see 2 places to get it:

1. odb owner provided one.
http://scm.codesynthesis.com/?p=odb/odb-etc.git;a=tree;f=binary/redhat;h=f277c92f7999f12438115b7d40b02d56d9172907;hb=93187055336c32812474400f7ac296b16bd4706a
That's not part of the git clone of:  git://scm.codesynthesis.com/odb/odb.git

2. And the fedora packager has one as well as part of git://pkgs.fedoraproject.org/odb.git

As I would want to keep in sync with the upstream repo, and rebuilt the rpm every now and then, I'm not sure how to go about this?

**Comment by finjulhich** [comment]
I took the fedora packager odb.spec file and I just copied in SOURCES/odb.
Changed the version to 2.5.0a as the odb developer did.

The spec file has a Source0: url which shows where to download the .tar.gz for odb,
but in my case, I don't need that. I already cloned the git repo instead.

I don't see this 'Source0' actually referenced elsewhere in the .spec file so I assume it has a particular meaning?

**Comment by Hubbitus** [comment]
I also come to searches way do that.

Problem there what `tito` expect sources in repository which he try build. So he do git archive , upload resulted tarball (copy to temp directory) and replace `Source0` tag in spec file.
It will not work for Fedora repos because there no sources in repository. Instead tarballs uploaded in lookaside cache (dist server) and referred as `Source[0-N]`. Also there may be several `Patch[0-N]`. So it is incorrect just replace `Source0` in `spec` file!

It will be good to see said some option how to produce srpm for build or build command (may be both). We may then provide there something like "fedpkg --srpm" or "fedpkg local".

Briefly look to builders concept I realize it may be accomplished by implementing new one, is not? If it already possible, could someone write short guide how to setup that?

**Comment by xsuchy** [comment]
You are mixing two concepts here.
When you work with dist-git you **must** use fedpkg (or some of its clones).
Tito is for creating releases from **upstream source git**. I.e. you work directly on source files and you make tar/gem/rpm and release it. There is even releaser which can upload the result into Fedora dist-git and call fedpkg build in some branch so you do not need to call it manually. But the starting point is always git with upstream files and not dist-git.

If you are working on some downstream project I encourage you to check tito.distributionbuilder.DistributionBuilder (see man tito.props), which comes in pair with ReleaseTagger. It create tar.gz from last tag where release number is zero and then generate patches. So while you have the benefits of working on unpacked sources, it always create pristine tar and generate the patches for you.

**Comment by Hubbitus** [comment]
I end up in exact situation as reporter of this ussue, I would create copr repo for some versions of packages which I also maintain in Fedora. That's versions which can't be updated in stable Fedora branches by our update policy.
So I would see repository equal by structure to Fedora (I even use 2 git remotes to pull changes).
As it is copr repo, it will be very cool to build package by commit, for what I setup webhook. The problem there dist-git. But really not dist-git exactly. I want see configurable command to obtain some tarball (really just download from upstream by provides commit hash) and then build it with provided command (let it be fedpkg, mock, koji or some other). And off course it good to see additional stuff which tito provides like easy tag creation.

**Comment by xsuchy** [comment]
Next version of rpkg (1.41) - dependency of fedpkg - will be able to build directly in Copr using command: fedpkg copr-build. This may be solution for you.
Or maybe wait until we open dist-git in Copr for users, but this will take some time as we do not want to publish something which is not ready.

**Comment by Hubbitus** [comment]
fedpkg copr-build is good news, i'll be happy try it for manual test builds instead of koji. But it does not solve problem build in copr by commit in git (github).

Could you please say is that possible archive what I want now configure existing builders and releasers of tito without [much] python programming?

**Comment by FrostyX** [comment]
Copr is a much more mature project now and supports building from multiple sources, not just from linked/uploaded SRPM. It can build from git repositories and DistGit repositories. In both cases, it is possible to specify a commit/branch to build from.

- https://docs.pagure.org/copr.copr/user_documentation.html#scm
- https://docs.pagure.org/copr.copr/user_documentation.html#distgit

I think we can safely close the issue now.
