### ISSUE TITLE
tito doesn't check its arguments carefully and --help is ignored

### ISSUE THREAD

**Issue by pavlix** [rpm-software-management/tito#215]
A program should never perform any actions when `--help` is among the command line arguments. It must either show the right help or say that `--help` is unsupported.

```
$ tito
Usage: tito MODULENAME --help
Supported modules:
   build    - Build packages.
   init     - Initialize directory for use by tito.
   release  - Build and release to yum repos
   report   - Display various reports on the repo.
   tag      - Tag package releases.
$ tito init --help 
Creating output directory: /tmp/tito
Creating tito metadata in: /home/pavlix/fedora/netresolve/.tito
   - created /home/pavlix/fedora/netresolve/.tito
   - wrote tito.props
   - created /home/pavlix/fedora/netresolve/.tito/packages
   - wrote /home/pavlix/fedora/netresolve/.tito/packages/.readme
   - committed to git
```

**Comment by FrostyX** [comment]
Related to #187

**Comment by FrostyX** [comment]
Hello @pavlix,
thank you for the report. This issue was already fixed.

    [jkadlcik@localhost project with space]$ tito init --help
    Usage: tito init [options]

    Options:
    -h, --help            show this help message and exit
    --debug               print debug messages
    --offline             do not attempt any remote communication (avoid using
			    this please)
    -o OUTPUTDIR, --output=OUTPUTDIR
			    Path to write temp files, tarballs and rpms to.
			    (default /tmp/tito)
