### ISSUE TITLE
Kernel srpm

### ISSUE THREAD

**Issue by cass00** [rpm-software-management/tito#235]
Creating an srpm from a kernel repo does not work. Repo to test with is `https://github.com/cass00/fedora-surface-pro-3-kernel/tree/tito_test`.
Command used:
`tito build -o /some_folder --srpm --debug --no-cleanup`
 Error message is error: 
`File /some_folder/rpmbuild-kernel6cson9d6/SOURCES/linux-4.6.tar.xz: No such file or directory`
It seems that tito doesn't (down)load the kernel source file (`linux-4.6.tar.xz`). Creating  an srpm with `fedpkg --dist f24 --module-name kernel -vvvv srpm` works.

**Comment by xsuchy** [comment]
Tito has different workflow from fedpkg. It does not download Source0, nor any other sources. It assume that sources are presented in git (expanded). And during build it call git-archive and pass it to Source0 (very simplified).

**Comment by FrostyX** [comment]
I remember some recent patches that could have make the use-case work. I cannot reproduce it though, since `https://github.com/cass00/fedora-surface-pro-3-kernel/tree/tito_test` doesn't exist anymore. I'll close, feel free to reopen if this is still an issue.
