### ISSUE TITLE
how does tito determine the name of a package?

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/tito#297]
I have a _subdir-per-package_ style tito repo of mostly Python packages.  Looking in `.tito/packages/` for the git repo, I see that while all of the packages are using a _python-_ prefixed name, I have one that is not.  It is using the bare PyPi module name.

So the question becomes how did this happen?  How does tito determine the name for a package?

And then, how can I correct this?  Can I simply `git mv .tito/packages/foo .tito/packages/python-foo`?

**Comment by xsuchy** [comment]
The answer is... it depends. See the code:
  https://github.com/dgoodwin/tito/blob/master/src/tito/common.py#L780
Usually it just query the spec file. If you rename the package I just recommend to tag it again it will work.

**Comment by dgoodwin** [comment]
Additional note, this is one of the first things I want to chance in effort
to support non-rpm builds. Hopefully that will soon rely on some other
options, explicit config, directory name, etc.

**Comment by FrostyX** [comment]
Since this is a question and the correct answer was IMHO already provided by @xsuchy, I am closing it now.

If there is any bug or missing feature regarding package names, feel free to submit a new issue @brianjmurrell.
