### ISSUE TITLE
Support for full timestamps for RPM changelogs

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/tito#305]
Currently, tito only supports the regular changelog date format (like `Wed Nov  1 2017`). However, since RPM 4.14, the full date structure is now supported (like `Wed Nov  1 11:08:13 EDT 2017`) for changelog entries.

Can a setting be added to support this for changelogs?

**Comment by xsuchy** [comment]
RPM 4.14 means F27+. The changelog generated by Tito should be readable by RHEL6 as well. So definitely not as default. I can imagine that this can be driven by some config option.

**Comment by Conan-Kudo** [comment]
@xsuchy Yes, that's why I asked for a setting. :)

**Comment by FrostyX** [comment]
@Conan-Kudo would you find more useful to have a configuration option to toggle between regular/full  (date/datetime) date or rather have a configuration option to define a custom date format string?

**Comment by Conan-Kudo** [comment]
@FrostyX A toggle. RPM only supports two variations, so a toggle is sufficient.
