### ISSUE TITLE
remove --define "_source_filedigest_algorithm md5

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/tito#331]
AFAIK the `--define "_source_filedigest_algorithm md5` has been used in code because EL5 understand only md5 checksum. As EL5 has been EOLed for more than a year. I guess this can be safely removed now.

Note that is used on several places in main.py

**Comment by FrostyX** [comment]
I guess you meant both `_source_filedigest_algorithm` and `_binary_filedigest_algorithm`
