### ISSUE TITLE
Active tito developers, please raise your hands

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/tito#355]
Hello guys,

if you have notifications for this project, you may have noticed increased activity in the last couple of weeks. At this point, I have resolved almost all pull requests that were hanging here for a very long time and soon I will go bug-hunting.

https://github.com/dgoodwin/tito/milestone/1

In this issue, I would like to see who is or wishes to be an active tito contributor. Apparently, without intending to, I got myself into leading this project. I will continue to do so until other stable contributors emerge and then we can lead the project as a team, instead of me being a benevolent dictator.

I am going to tag here all contributors that committed at least once to this project. If you want to get involved in the forthcoming development, please let me clearly know in this issue. We can then exchange contacts and create a plan what needs to be done.

Please tag also other people that might be interested.

Keep in mind that there are many ways to contribute, not just coding. Personally I would find very valuable and appreciate someone who can just review (my) pull requests. But we could also use some help with documentation, testing, ... 

I am going to close this issue after two weeks, that means
8th of April, 2020.

Thank you and looking forward to working with you,
FrostyX

**Comment by FrostyX** [comment]
- @dgoodwin 
- @xsuchy 
- @awood 
- @jumanjiman 
- @stevekuznetsov 
- @jmrodri 
- @FrostyX 
- @msehnout 
- @KenMacD 
- @jbowes 
- @evgeni 
- @Conan-Kudo 
- @ashcrow 
- @maxamillion 
- @tjanez 
- @palli 
- @ignatenkobrain 
- @ehelms 
- @vfreex 
- @sosiouxme 
- @mstead 
- @mccun934 
- @lubomir 
- @jeckersb 
- @iNecas 
- @AdamWill 
- @vrutkovs 
- @venth 
- @mirekdlugosz 
- @lzap 
- @brenton 
- @bcl 
- @vbatts
- @twiest 
- @treydock 
- @tlestach 
- @stpierre 
- @slagle 
- @seanburlington 
- @schlupov 
- @ringerc 
- @pfournier 
- @mtinberg 
- @mscherer 
- @mbacovsky 
- @kahowell 
- @jflorian
- @grosskur
- @glensc 
- @ernestask

**Comment by FrostyX** [comment]
- @enaut 
- @domcleal 
- @dLobatog 
- @csonto 
- @cnsnyder 
- @cgwalters 
- @bby-bishopclark 
- @aronparsons 
- @adammhaile 
- @adamladd17 
- @RobberPhex 
- @Allda

**Comment by enaut** [comment]
Thank you for the ping. I'm currently hardly using tito :( so I will not really be part of a persistent team. As long as you are using git and the code is open source there is not really a big problem with the benevolent dictator model - I think. However I absolutely do understand your request for peer reviews.

**Comment by ernestask** [comment]
I don’t want to commit to anything (due to time constraints), but I can keep an eye on PRs and provide the occasional remark.

**Comment by kahowell** [comment]
@FrostyX thanks for the leadership in this area!

The Candlepin team (https://github.com/candlepin) still actively uses tito, so we'd like to give back by contributing a limited amount of time for reviews. If you tag myself, @cnsnyder, @wottop, @barnabycourt in PRs, we'd be happy to give some time for reviews to keep tito going; note: there are others on our team we may get involved, but having us 4 tagged would make sure we get it on our sprint plans.

**Comment by FrostyX** [comment]
@ernestask @kahowell, I believe there should be some "watch" button that allows you to subscribe to a notification about new pull requests in a project. Would you consider that? After the initial bugfixing milestone that I linked above, there shouldn't be that much traffic in the project, that would bother you.

**Comment by ernestask** [comment]
Yup, I did that already (/me grumbles about the lack of fine-grained controls on GitHub).

**Comment by Conan-Kudo** [comment]
I'm actively using it with DNF and Spacewalk/Uyuni...

**Comment by Conan-Kudo** [comment]
@FrostyX Have you considered moving it out of dgoodwin namespace and into its own `tito` namespace?

**Comment by dgoodwin** [comment]
> @FrostyX Have you considered moving it out of dgoodwin namespace and into its own `tito` namespace?

FWIW I am ok  with this and my apologies for having to step away from the project, I haven't been a tito user for 5 years and it started to show in the quality of maintenance.

I am happy to relinquish the repo and help redirect people.

**Comment by FrostyX** [comment]
> @FrostyX Have you considered moving it out of dgoodwin namespace and into its own tito namespace?

Since there are no side-projects and at this point, we would have just tito/tito and nothing else in that namespace, I think it's not worth it. But if we vote or something and you would prefer this option, I am not against it.

**Comment by ernestask** [comment]
/me votes for tito/tito to make it more “official”.

**Comment by jmrodri** [comment]
@jmrodri here! I'd like to remain present. I still use tito not as much as I used to.

**Comment by jmrodri** [comment]
Also, I agree tito/tito would be nice

**Comment by jflorian** [comment]
I use tito nearly daily so tend to hang here mostly to be aware, but occasionally to submit bug rpts &| patches.

**Comment by jflorian** [comment]
> it’s likely unlikely

error: cannot parse

**Comment by ernestask** [comment]
> > it’s likely unlikely
> 
> error: cannot parse

Good, it was to thwart any possible bot attacks.

**Comment by mtinberg** [comment]
Thanks @dgoodwin for all the hard work over the years and @FrostyX for wanting to take ownership.  Moving to tito/tito namespace makes sense to me, and I use tito for ~150 internal packages within my organization, it does all the heavy lifting of our Gitlab CI.  I'd be happy to submit patches if I ever have another issue with our CI process, it's been working well for us for a while.

**Comment by FrostyX** [comment]
Thank you guys for your responses!

Honestly, I didn't expect such positive feedback at all. I thought that there will be radio silence for two weeks and then that I would quietly close the issue like nothing happened. It is the exact opposite. Thanks!

I am also very happy that many of you use tito at such scale.

I've been thinking, there are many people interested in at least being up-to-date with what is going on. What would you say on me registering a `#tito` channel on `irc.freenode.net`? Will I be there alone or can we idle there together?

**Comment by bcl** [comment]
I'm still using tito with lorax, I can try to look at PRs as time allows.

**Comment by bby-bishopclark** [comment]
@mtinberg 
> it does all the heavy lifting of our Gitlab CI

If it's not there already, a quick doc to show how this is all set up would be neat.  There are a dozen half-finished docs out there, but it'd be nice to have one in the project.  My own CI->tito setup has been back-burnered for many #reasons

@FrostyX 
> a #tito channel on irc.freenode.net

I'd loiter harder on a slack channel, but that's because I have that client installed and ignored.  I don't even have an IRC app.  Maybe #matterbridge can help, but that's a long ways off too.

**Comment by mtinberg** [comment]
> @mtinberg
> 
> > it does all the heavy lifting of our Gitlab CI
> 
> If it's not there already, a quick doc to show how this is all set up would be neat. There are a dozen half-finished docs out there, but it'd be nice to have one in the project. My own CI->tito setup has been back-burnered for many #reasons

This isn't particularly exciting but here it is

```yaml
centos7-test:
  stage: build
  script:
  - "tito release --test yum-el7-ns-testing"
  except:
  - /^packagename-.*$/
  tags:
  - centos7
centos7-prod:
  stage: build
  only:
  - /^packagename-.*$/
  script:
  - "tito release yum-el7-ns"
  tags:
  - centos7
```
With tito installed on the host running gitlab-runner and ssh key auth setup for rsync using a restricted shell (rssh) to the web server where the yum repo is hosted.  On the gitlab runner we have a post-job command that calls spacewalk over the API and refreshes its repos `spacewalk.channel.software.syncRepo(key, channel.get("label"))`.

So the tito releasers are the same for every project, and the gitlabci config just changes the regex for matching tags to know whether to do a test build or not.  the build server just runs gitlab runner and has all of *-devel-* rpms installed so we don't have problems with that.

**Comment by FrostyX** [comment]
> /me votes for tito/tito to make it more “official”.

Just FYI tito namespace is taken by some user, we would have to take something less pretty.

**Comment by Conan-Kudo** [comment]
@FrostyX `tito-tool/tito`?

**Comment by jumanjiman** [comment]
i use it a _little_ still, but not actively in my current role

**Comment by jumanjiman** [comment]
> > /me votes for tito/tito to make it more “official”.
> 
> Just FYI, tito namespace is taken by some user, we would have to take something less pretty.

i just squatted on `rpmkit` and `rpm-kit` as organization names.

if the group decides they want to move tito to one of these namespaces, i'll transfer ownership to the group.

**Comment by ernestask** [comment]
What about rpm-software-management, where mock, dnf et al live?

**Comment by ernestask** [comment]
> Thank you guys for your responses!
> 
> Honestly, I didn't expect such positive feedback at all. I thought that there will be radio silence for two weeks and then that I would quietly close the issue like nothing happened. It is the exact opposite. Thanks!
> 
> I am also very happy that many of you use tito at such scale.
> 
> I've been thinking, there are many people interested in at least being up-to-date with what is going on. What would you say on me registering a `#tito` channel on `irc.freenode.net`? Will I be there alone or can we idle there together?

I would idle there.

**Comment by tlestach** [comment]
tito has been used by [Spacewalk](https://github.com/spacewalkproject/spacewalk) developers and Satellite 5 Engineering for years, but since Red Hat Satellite 5 End Of Life is on [May 31, 2020](https://access.redhat.com/support/policy/updates/satellite) and with this move Spacewalk will be discontinued as well, this user base will be lost. Thanks for the tool, it's been a tremendous help that made our life easier over the years!

**Comment by xsuchy** [comment]
I am trying to watch issues. I barely have time to review PR's. If you want I can create a project under https://github.com/rpm-software-management/ organization. Thou, it may be a little misleading as nowadays you can release other artifacts than rpm itself with Tito.

**Comment by FrostyX** [comment]
> I'd loiter harder on a slack channel, but that's because I have that client installed and ignored. I don't even have an IRC app. Maybe #matterbridge can help, but that's a long ways off too.

Although I see some of the slack advantages, AFAIK the whole Fedora uses IRC. So personally I would rather stick with that until someone decides about global migration.

**Comment by vfreex** [comment]
+1 for moving this project to rpm-software-management org. Although tito can release more than RPMs, I think it is more rpm centric and it's nice to be under the umbrella of rpm-software-management.

OpenShift is also using tito to manage a lot of RPM packages. I would also like to help improve this project in my spare time.

**Comment by xsuchy** [comment]
@FrostyX I set up https://github.com/rpm-software-management/tito I made you admin there. Feel free to populate it and add other people there.

**Comment by Conan-Kudo** [comment]
@xsuchy @FrostyX It'd be better to transfer _this_ repository to `rpm-software-management` so that the issues and the fork network come along for the ride.

**Comment by dgoodwin** [comment]
Is this what we want? https://help.github.com/en/github/administering-a-repository/transferring-a-repository I have the transfer setting available.

If so it looks like we need the tito repo deleted in the new org so it can work. @FrostyX @xsuchy let me know if and when you'd like me to initiate the transfer.

**Comment by FrostyX** [comment]
@dgoodwin we are waiting for a confirmation from rpm-software-management guys and then let you know.

**Comment by dmach** [comment]
@dgoodwin I deleted the empty tito repo in rpm-software-management org.
You can transfer the repo now. If you bump into any issues, let me know.

**Comment by dgoodwin** [comment]
"You don’t have the permission to create public repositories on rpm-software-management"

Could you temporarily grant me permissions over there?

**Comment by dgoodwin** [comment]
Repo transferred!

**Comment by FrostyX** [comment]
Great, thank you @dgoodwin and @dmach

**Comment by FrostyX** [comment]
@dmach will you create also https://copr.fedorainfracloud.org/coprs/g/rpm-software-management/tito/ for us, please?

**Comment by FrostyX** [comment]
Hello guys,
I would like to thank you all for the positive feedback and discussion here. I am very happy, that many of you are still interested in Tito (as either developers or users). I would like to wrap up with the following points

- The Copr project for Tito https://copr.fedorainfracloud.org/coprs/g/rpm-software-management/tito/ was created. Whoever needs permissions for it, please request them in the project settings
- The `#tito` channel on `irc.freenode.net` was registered. If you are an IRC user, please update your autojoin list of channels and idle there with us. I expect it to be a pretty low-traffic channel so you don't have to be worried about being constantly spammed. It will be useful when trying to move forward with the project.

> I am going to close this issue after two weeks, that means
> 8th of April, 2020.

As promised, I am closing the issue now.
See you on IRC :metal:
