### ISSUE TITLE
MD5 sum mismatch when building on EL5 

### ISSUE THREAD

**Issue by evgeni** [rpm-software-management/tito#381]
Since 0.6.14, SRPMs generated by tito fail to build on EL5 for me :(

The koji error I see is:

```
error: unpacking of archive failed on file /builddir/build/SPECS/pulp-rpm.spec;5f0c432b: cpio: MD5 sum mismatch
```

Still digging it further, but thought you'd like a heads up :)

cc @pcreech

**Comment by evgeni** [comment]
My best guess, looking at the git log, is that that's because of 40287ca668539edcca0e519657f9540f3703f894

**Comment by xsuchy** [comment]
Yes. That is the culprit. EL5 is EOLed for some time. If you want to build for EL5 then you must use some old version of tito or backport that change back.

**Comment by evgeni** [comment]
Is there a way to pass rpmbuild params in `tito.props`?

**Comment by xsuchy** [comment]
Nope.
