### ISSUE TITLE
Can KojiReleaser with builder.test=1 use Koji's new (1.21) --no-rebuild-srpm option?

### ISSUE THREAD

**Issue by jflorian** [rpm-software-management/tito#382]
Koji-1.21 now [allows skipping SRPM rebuild for scratch builds](https://pagure.io/koji/pull-request/2083).  This seems perfect to me for doing quicker test builds.  I'm not sure if there would be any downsides.

**Comment by FrostyX** [comment]
Hello @jflorian,
thank you for bringing this topic up.

Since the PR you mentioned revolves around scratch builds, what do you say if we use the `--no-rebuild-srpm` when Tito release is called with `--scratch` parameter? Instead of relying on `builder.test=1`.

**Comment by jflorian** [comment]
@FrostyX to be honest, I'm not clear as to what the difference between `builder.test=1` and `--scratch` is.  Up to this point, I've not used `--scratch` at all.  I tried it once today, but I can't say I noticed a difference.  I just now read from the [Koji HOWTO](https://docs.pagure.org/koji/HOWTO/#build-options) where it says:
> This makes the build into a scratch build. The build will not be imported into the db, it will just be built. The rpms will land under <topdir>/scratch. Scratch builds are not tracked and can never be tagged, but can be convenient for testing. Scratch builds are typically removed from the filesystem after one week.

So those sound useful but generally I use test builds instead so that they land in a dnf repo for easy installation and testing.  So maybe, yes you are right to tie this with `--scratch`.  However, it seems `builder.test=1` would benefit just as well ... if it's possible.  Maybe there are reasons not to do this though, even if it is possible.  I wish I knew more.

**Comment by FrostyX** [comment]
@jflorian Do you think you could test Tito from PR #385?

**Comment by jflorian** [comment]
This isn't working for me.  I tried integrating this change on top of my installed tito-0.6.15-1.fc31.noarch and also from a git clone running bin/tito-dev and in both cases, the added condition doesn't pass because `self.test=None` (as confirmed with an added `print` call).  I double checked my `releasers.conf`:
~~~
[test-fedora-32]
releaser = tito.release.KojiReleaser
autobuild_tags = f32
builder.test = 1
~~~
