### ISSUE TITLE
copy_extra_sources doesn't handle remote URLs well

### ISSUE THREAD

**Issue by evgeni** [rpm-software-management/tito#387]
Ohai,

in our spec files, we use `SourceX: https://some.example.com/artifact.tar.gz` as sources, but the new `copy_extra_sources` code fails on that:

```
      File "/usr/lib/python3.8/site-packages/tito/builder/main.py", line 217, in srpm
        self.copy_extra_sources()
      File "/usr/lib/python3.8/site-packages/tito/builder/main.py", line 516, in copy_extra_sources
        shutil.copy(src, self.rpmbuild_sourcedir)
      File "/usr/lib64/python3.8/shutil.py", line 415, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib64/python3.8/shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tito/…'
```

We're using a (derived) `GitAnnexBuilder` so I have a hunch that maybe `NoTgzBuilder` should just have a `pass` as `copy_extra_sources`?

**Comment by FrostyX** [comment]
Thank you for the feedback @evgeni.

>  so I have a hunch that maybe NoTgzBuilder should just have a pass as copy_extra_sources

Possibly

There is a debug output just before the line that caused your traceback.

    debug("Copying %s -> %s" % (src, self.rpmbuild_sourcedir))

I am curious, what it is trying to copy?

**Comment by evgeni** [comment]
```
Copying /tmp/tito/rpmbuild-x7dtzde5b/SOURCES/x-1.2.3/https://rubygems.org/gems/concurrent-ruby-1.1.5.gem -> /tmp/tito/rpmbuild-x7dtzde5b/SOURCES
```

Where `https://rubygems.org/gems/concurrent-ruby-1.1.5.gem` is `Source1`

**Comment by FrostyX** [comment]
Thank you. Then what about if we put these two lines

    debug("Copying %s -> %s" % (src, self.rpmbuild_sourcedir))
    shutil.copy(src, self.rpmbuild_sourcedir)

into a condition and copy things only if the `src` file exists.

**Comment by evgeni** [comment]
Would certainly work, yeah. There is also a "similar" skipping block a few lines above, when `dst_file` already exists.
