### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by webknjaz** [rpm-software-management/tito#404]
Hi, any reason this project isn't on PyPI?

As a user of a non-RPM-based OS, being able to `pip install tito` would be a great deal for me trying out this tool.
Sure, I can install it in a container to play one time but it's not really ergonomic UX/DX-wise.

FWIW, if you folks aren't opposed to the idea, I can contribute GHA-based automation. To get a rough idea of what it'd look like, see https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

**Comment by FrostyX** [comment]
@webknjaz sure, that's a good idea, thank you for the suggestion. There appears to be some issue with the package name though, I will try to resolve it.

**Comment by FrostyX** [comment]
Hello @dgoodwin,
by any chance, do you have the `tito` PyPI name registered? It doesn't return anything for https://pypi.org/project/tito/ but according to people on `#python`, it still can very well be registered to someone and just doesn't contain any files.

**Comment by webknjaz** [comment]
It gets registered on the first upload unless it's very ancient. I would guess that it may be in PyPI's blocklist if somebody attempted to abuse it in the past.

FWIW if you file a PEP 541 request at https://github.com/pypa/pypi-support/issues/new/choose, the PyPI admins should be able to help you out and unblock/release it for you. Keep in mind that those folks are volunteers and it may take weeks to get it done.

**Comment by dgoodwin** [comment]
Hey, apologies but I don't think it was me. I have no memory of uploading to pypi at any point and I don't have any creds in my pw manager or browser. :(

**Comment by FrostyX** [comment]
Thank you guys,
just wanted to ask @dgoodwin first because that could have been the easiest resolution without having to bother the PyPI people but I am going to file a request like @webknjaz is suggesting.

**Comment by FrostyX** [comment]
I filled the PEP 541 request, so now we need to wait.
https://github.com/pypa/pypi-support/issues/1079

**Comment by Etheryte** [comment]
@FrostyX It seems that the request was successful, is adding the project to PyPI still something you would consider?

**Comment by FrostyX** [comment]
Thank you for pinging me @Etheryte.
I pushed to PyPI https://pypi.org/project/tito/

**Comment by FrostyX** [comment]
There is also a missing description in the PyPI project, should be fixed by #418.
