### ISSUE TITLE
[Feature Request] Add support for gpg signing to `tito tag`

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/tito#415]
Can you please add the ability to gpg sign the tag and commit that are created by `tito tag`?

**Comment by xsuchy** [comment]
This is already possible.

`man tito.props` and search for `sign_tag`

I.e.,
```
[buildconfig]`
sign_tag = true
```
will work.

**Comment by gotmax23** [comment]
> This is already possible.
> 
> `man tito.props` and search for `sign_tag`
> 
> I.e.,
> 
> ```
> [buildconfig]`
> sign_tag = true
> ```
> 
> will work.

Does this also sign the commit (`git commit -S`)?
