### ISSUE TITLE
Bodhi updates via releaser while doing `tito release`?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/tito#428]
Can we make this possible?  Bodhi is the only manual step we are doing while releasing packages into Fedora.
It is quite easily to submit bodhi using `fedpkg update` (one command => one update template => many packages in multiple Bodhi updates).  Seems like something tito could automatize.

**Comment by praiskup** [comment]
@xsuchy fyi

**Comment by xsuchy** [comment]
There is python bindings in bodhi-client package.

**Comment by FrostyX** [comment]
I really like the idea
