### ISSUE TITLE
  how can i pass the --no-clean in mock to the tito command?

### ISSUE THREAD

**Issue by LinglingXiang** [rpm-software-management/tito#435]
hi everyone,

If anyone can help and have a look at ?

currently i meet one issue,  how can i pass the --no-clean in mock to the tito command?

i need build an rhel8 package of A, as some packages are missing from one repo, so i locally download the packages and use the steps

mock -r rhel8.cfg --init
 mock -r rhel8.cfg --install python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64.rpm
mock -r rhel8.cfg --install python36-devel-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64.rpm
then i use mock 
mock -r rhel8.cfg  /root/rpmbuild/A.src.rpm  --no-clean

it will build rhel8 packages successfully

but i need use tito to build, then how can i pass the --no-clean to the tito command?

tito build --output=/root/rpmbuild --rpm --offline --test --builder=mock --arg=mock=rhel8.cfg

**Comment by FrostyX** [comment]
Hello @LinglingXiang,
I guess you are running `tito` something like this

    tito build --rpm --arg mock=rhel8.cfg

You can add the following parameter your command

    --arg mock_args="--no-clean --no-cleanup-after"

**Comment by LinglingXiang** [comment]
@FrostyX, thanks for your answer, that is what i want!

**Comment by FrostyX** [comment]
Seems that this is fixed but I forgot to close the issue.
