### ISSUE TITLE
BUG : first source is always ignored

### ISSUE THREAD

**Issue by Malix-Labs** [rpm-software-management/tito#505]
Hey

I am either crazy or hit a off-by-one error

This :

https://github.com/Malix-Labs/gsk-renderer-gl-patch/blob/ff27e47e9c393941ebafe6178d16eca35864db29/gsk-renderer-gl-patch.spec#L1-L5

```spec
Source0: src/main.sh 
Source1: lib/set.sh 
Source2: lib/revert.sh 
Source3: lib/reboot.sh 
Source4: lib/variables.sh 
```

And `tito build --test --no-cleanup --srpm` outputs this :

![image](https://github.com/user-attachments/assets/d13640b3-27d1-4a5f-8cd1-7c6bc1c90830)

**But**

This : 

https://github.com/Malix-Labs/gsk-renderer-gl-patch/blob/f5a1b5a709cc5de8215557e45031a98cafcc8d47/gsk-renderer-gl-patch.spec#L1-L5

```spec
Source1: src/main.sh 
Source0: lib/set.sh 
Source2: lib/revert.sh 
Source3: lib/reboot.sh 
Source4: lib/variables.sh 
```

And `tito build --test --no-cleanup --srpm` outputs this :

![image](https://github.com/user-attachments/assets/e8c90c40-cc41-4ed0-86ae-8fb7ca5a0abf)

I also tested it with all numbers higher than 0, and it was the same result:
The first source gets ignored

What is happening ?

**Comment by Malix-Labs** [comment]
## **Please help**

**Comment by praiskup** [comment]
Hello, with Tito, the first Source is usually a tarball created by git archive. In this case, it's replaced with: Source0: gsk-renderer-gl-patch-git-11.ff27e47.tar.gz.

In other words, you typically don't need to specify each file with a Source statement. You let Tito pre-create the tarball, and then extract it in the %prep section.

**Comment by praiskup** [comment]
That said, the tarball contains all the files in git tree...  sorry I clicked on "close" by mistake, but I think we can leave it closed. Please reopen if you disagree.

**Comment by Malix-Labs** [comment]
> Hello

Hello @praiskup, and thanks for taking the time to help me ! :heart:

> Hello, with Tito, the first Source is usually a tarball created by git archive. In this case, it's replaced with: Source0: gsk-renderer-gl-patch-git-11.ff27e47.tar.gz.

Indeed !

The first source used (so not always `Source0`) always gets replaced:

For example, even if I used :
```spec
Source2: src/main.sh 
Source3: lib/set.sh 
Source4: lib/revert.sh 
Source5: lib/reboot.sh 
Source6: lib/variables.sh 
```
`Source2` would get replaced with the tarball file

I find that behaviour highly confusing

> Typically don't need to specify each file with a Source statement

That's interesting and nice to know
What would specifying source would serve for, idiomatically ?

> You let Tito pre-create the tarball, and then extract it in the %prep section.

In my case, the only thing I am shipping are shell scripts, so nothing needs to be compiled.
In that case, should I still use the tarball instead?

I have an hard time understanding how to code [my spec file](https://github.com/Malix-Labs/gsk-renderer-gl-patch/blob/main/gsk-renderer-gl-patch.spec) with that design

**Comment by praiskup** [comment]
You typically want one [Source](https://github.com/fedora-copr/vcs-diff-lint/blob/25fe4875f7882f8be60ad18e09e874be241b74ee/vcs-diff-lint.spec#L16-L19), which you extract with [setup](https://github.com/fedora-copr/vcs-diff-lint/blob/25fe4875f7882f8be60ad18e09e874be241b74ee/vcs-diff-lint.spec#L51).

With this, you just fix the `install` statements to not use `SourceN` but regular filenames. Try to call `/bin/find` in `%install` section to observe what you get.

**Comment by Malix-Labs** [comment]
Okay, thanks @praiskup, will test that !

Is there a way to not create a tarball to enhance performance, or would it always be created no matter what settings I put ?

**Comment by praiskup** [comment]
> Is there a way to not create a tarball to enhance performance, or would it always be created no matter what settings I put ?

I don't think there's such an option.  Tito simply wraps git repo into a release tarball + some convenient steps.

Maybe I generalize a bit now, but you probably want to distribute your software as a tarball, so also non-RPM distributions may adopt the software easily.  Then, doing software release properly is an expensive process where "performance" is the thing you care about the least.

**Comment by Malix-Labs** [comment]
Understood, thanks for your advices

**Comment by Malix-Labs** [comment]
Btw, I noted that there is already an archived source by default :

![image](https://github.com/user-attachments/assets/d13640b3-27d1-4a5f-8cd1-7c6bc1c90830)

What is "setup" for ?

**Comment by praiskup** [comment]
Best answered by [RPM docs](https://rpm-software-management.github.io/rpm/manual/spec.html):

%prep prepares the sources for building. This is where sources are unpacked and possible patches applied, and other similar activies could be performed.

Typically [%autosetup](https://rpm-software-management.github.io/rpm/manual/autosetup.html) is used to automatically handle it all, but for more advanced cases there are lower level %setup and %patch builtin-macros available in this slot.

**Comment by Malix-Labs** [comment]
Hey @praiskup, can you help me?
I am absolutely desparate to make https://github.com/Malix-Labs/gsk-renderer-gl-patch/blob/f5abbce1f8abdca4219d2178991d726f71f82f1e/gsk-renderer-gl-patch.spec work, but I am not able despite having tried really hard since a long time
I get a cryptic
```log
RPM build errors:
    Empty %files file /tmp/tito/rpmbuild-gsk-renderer-gl-patchcms9bwlm/BUILD/gsk-renderer-gl-patch-1.0.1-build/gsk-renderer-gl-patch-git-14.ca87803/debugsourcefiles.list
```
error rn

**Comment by FrostyX** [comment]
@Malix-Labs this looks unrelated to Tito to me, I think you need to add this line into the first part of your specfile

```
BuildArch: noarch
```

**Comment by Malix-Labs** [comment]
Thanks @FrostyX, it seems to work now !

However, neither the log output or `rpmlint` helped me catch that,
Do you know where i could submit that as an issue ?

**Comment by praiskup** [comment]
The tracker is probably https://github.com/rpm-software-management/rpm, though that error report might be hard to make better.  The %files section was empty, per `debugsourcefiles.list` (search for %files -f option), which means "debuginfo/debugsource" sub-package related… rpm creates these sub-packages for arch-specific packages... Which means that you try to generate an arch-specific package.  And since you actually don't want to do that (the package we talk about is just a set of arch-agnostic scripts), you need to switch the build to prepare arch-agnostic package (noarch == that's what @FrostyX suggested).

Some generative AI would probably help here, otherwise it requires some kind of package maintenance knowledge.

**Comment by Malix-Labs** [comment]
Thanks for the clarification

I did not have any `BuildArch` field before, does that mean that its default behaviour is multiarch ?

Wouldn't that be a good idea to require the definition of `BuildArch` ?

_Please accept my apologies if that's a dumb suggestion, I'm very new to RPM packaging_
